### ISSUE TITLE
[Bug] バグタイトル: helpの検索が使えない

### ISSUE THREAD

**Issue by narikakun** [SinaKitagami/program-team#101]
## バグ詳細⚠
helpの検索機能が使えない。

## 実行コマンド
s-help → 虫眼鏡をクリック → 検索文字列を入力 → エラー

## スクリーンショット
![image](https://user-images.githubusercontent.com/35885585/129911332-a5b2ad81-83c4-4ce9-b775-7317f8f10f43.png)

## エラー詳細
```
Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'lang/<coroutine object LocalizedContext.user_lang at 0x7f52072c69c0>.json'
```

**Comment by apple502j** [comment]
user_langのawaitし忘れ?

**Comment by Midorichaan** [comment]
修正しました
正常に動作するか、ご確認をお願いします。

Midorichan
