### ISSUE TITLE
[Bug] usersやguildsがシャード単位でのみ操作される

### ISSUE THREAD

**Issue by yaakiyu** [SinaKitagami/program-team#111]
## バグ詳細⚠
起動ログ及びbotinfoなどの`bot.users`や`bot.guilds`、`bot.get_user`や`bot.get_guild`にアクセスする機能において、実行したサーバーのシャードにおける情報しか表示されない。`fetch_user`を用いる`information user`コマンドには影響がないとみられるが、一部情報(共有サーバーなど)が狂う。

## 重要度
1

## 代替案
新しい関数・変数を作りbot.shardsすべてで検索するようにする。

**Comment by T-taku** [comment]
Shardによって使える機能があったり、なかったりするのもまあまあ問題。

**Comment by yaakiyu** [comment]
PR出そうかと思ったけれどbotの定義部分がクラス継承ではなかったので少し大変そう...

**Comment by takumi0213** [comment]
現在はShardはこれまで通りの`AutoShardedBot`に修正し運用中です。
今後規模が拡大した場合に再度直面する可能性が高いIssueとしてなんらかの対応をもとめられると考えています。
